- name: retrive secrets
  hosts: localhost
  task:
    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=test/MYPASS  token={{ var.vault_token }} url=https://vault-internal-devrobo.online:8200 validate_certs=False')}}"
